cc_binary (
    name = "main1",
    srcs = ["main01.cpp"],
    copts = ["--std=c++17", "-O2"],
)

cc_binary (
    name = "main2",
    srcs = ["main02.cpp"],
    copts = ["--std=c++17", "-O2"],
)

cc_binary (
    name = "main3",
    srcs = ["main03.cpp"],
    copts = ["--std=c++17", "-O2"],
)

cc_binary (
    name = "main4",
    srcs = ["main04.cpp"],
    copts = ["--std=c++17", "-O2"],
)

cc_binary (
    name = "main5",
    srcs = ["main05.cpp"],
    copts = ["--std=c++17", "-O2"],
)

cc_binary (
    name = "main6",
    srcs = ["main06.cpp"],
    copts = ["--std=c++17", "-O2"],
)
